name: supabase_repository
description: A DatabaseAdapter for the supabase database as used by the database_repository package
version: 1.0.1
repository: https://github.com/glassp/supabase_repository

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  database_repository: ^1.2.1
  supabase: ^0.2.14
dev_dependencies:
  effective_dart: ^1.3.2